### ISSUE TITLE
Support for ember-data models.

### ISSUE THREAD

**Issue by ghost** [lcoq/ember-validations#5] opened 2012-10-16 17:54 UTC
Was it designed to work with ember-data as well?

**Comment by lcoq** [comment] 2012-10-16 18:02
For now, it can't work because ember-data already have an `errors` property.
I can rename it `validationErrors` (it corresponds to the opened issue #3), and I don't see any other reason to have conflict with.

But you'll have to use it "manually", I mean committing a model will not call the validations, you'll have to do it.

So my answer is no, its not designed to work with ember-data **for now**, even if it could, but I'm totally open to suggestions, or PR to make it work.

**Comment by ghost** [comment] 2012-10-16 18:13
:sob: Really wish it did, will try and re-implement this in ember-data. Thanks.

**Comment by lcoq** [comment] 2012-10-16 18:41
I'll change the `errors` property name really soon.

I'd like to see this project integrated into ember-data too, so I sought advices from the ember-data team: https://github.com/emberjs/data/issues/419.

If you want to try to re-implement it in ember-data alone, I just suggest you to read [Adapter errors PR by @tchak](https://github.com/emberjs/data/pull/376).

**Comment by ghost** [comment] 2012-10-16 19:00
@tchak's PR target's server side errors or? Could we then try and integrate this with ember-data? ... now that's its using 1.0 pre.

**Comment by lcoq** [comment] 2012-10-17 19:25
@kelonye yep, I guess the @tchak's PR will be merged, so, for example, `DS.ValidationError` will exist ([here](https://github.com/emberjs/data/pull/376/files#L3R5)), and we consequently can't use Ember.ValidationErrors defined in this library.
And about trying to integrate this with ember-data, I think it could be a good thing to wait some feedback from ember-data team before trying to make it work with ember-data.

**Comment by lcoq** [comment] 2012-10-23 15:55
The `errors` property is now renamed `validationErrors`, and should consequently works with ember-data.

**Comment by ghost** [comment] 2012-10-23 16:48
Awesome, been meaning to write a spec for this.

**Comment by lcoq** [comment] 2012-10-23 17:17
Ok, don't hesitate to tell me any error, unexpected behaviour, or possible improvement you see!

**Comment by ghost** [comment] 2012-10-23 19:01
Already running into issues http://goo.gl/7Sd8k (badly done). I guess should be asking, what version of ember-data should I test against? Haven't played with revision 5+.

**Comment by lcoq** [comment] 2012-10-23 19:23
You're not using the last version of ember-validations.
Pull all newer commits, change what I said [in this comment](https://github.com/kelonye/ember-validations/commit/f7ec3d06d12c8120a72d6de8dee237333a29607c#commitcomment-2040968).
Then, you can run a `rake clean` and a `rake test`. 
It should work.

And for now, ember-validations is made for ember v1.0pre, so I guess it will work for any version of ember-data which could work with ember 1.0pre.
Tell me if you've any problem, or if you don't have!

**Comment by ghost** [comment] 2012-10-23 20:19
Awesome http://goo.gl/stC7o.

Yeah, works with ember v1.0pre and ember-data revision 4. Considering maintaining such a spec for ember-data? ... Just to ensure support.

Considering merging this awesomeness with a fork of [ember-bootstrap](http://goo.gl/pu57q) . :thumbsup: . Up for a new mini repo?

**Closed as completed** 2012-10-23 20:21 UTC
Labels: question
