### ISSUE TITLE
I can not customize my validation error messages

### ISSUE THREAD

**Issue by zhangyuhui** [lcoq/ember-validations#32] opened 2013-11-08 21:14 UTC
How can I define my own error messages?

**Comment by lcoq** [comment] 2013-11-11 09:24
It depends on which kind of error message you wants to customize.

If you want to change all the error messages for `blank` errors, you can do: 

```
Ember.ValidationError.addMessage('blank', "my custom error message");
```

If you want to define a custom error message for a specific property, there is sadly no way to do that yet.

I close this issue as this is a duplicate of #13 .

**Closed as completed by lcoq** 2013-11-11 09:24 UTC
Labels: duplicate, question
